project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "posts/*.qmd"
    - "logs/*.qmd"
    - "!posts/2023-12-04-techno-optimisim.qmd"
    - "!posts/2025-01-30-job-search.qmd"
    - "!posts/2025-03-30-marvin-minsky-mit-lectures.qmd"
    - "!posts/2025-04-14-the-internal-external-mismatch.qmd"
    - "!posts/2025-04-15-loneliness.qmd"
    - "!posts/2025-04-23-losing-the-fight-for-privacy.qmd"
    - "!posts/2025-10-06-torn-apart.qmd"
    - "!posts/2025-11-05-hurrah-to-the-fallen-comrades.qmd"
    - "!posts/2026-05-10-playing-risk-with-neural-networks---part-1.qmd"
  resources:
    - CNAME
    - favicon.ico

website:
  title: "Exploring the digital universe"
  description: "I wander the digital universe, seeking the beauty in systems and patterns"
  site-url: "https://blog.osm-ai.net"
  google-analytics: "G-KXDBM0MM5V"
  favicon: favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - href: about.qmd
        text: About
      - href: phd-work.qmd
        text: PhD
      - href: alife.qmd
        text: Alife
      - href: logbook.qmd
        text: Logbook
    right:
      - href: index.xml
        text: RSS
      - href: https://github.com/osm3000
        text: GitHub

format:
  html:
    theme: journal
