---
title: View on Techno-Optimism
date: 2023-12-04 00:00:00 +0200
description: First reactions to techno-optimism, nuclear power, and the unintended effects of progress.
categories:
- thinking
draft: true
aliases:
- /thinking/2023/12/04/techno-optimisim.html
- /2023/12/04/techno-optimisim.html
---
My immediate thoughts are:
1. I liked the fact that someone said it. For some reason, in my surrounding / Europe (my perception at least), there is a since of looming doom and pessimism about the future and the role of technology. I always find this counter-intuitive, since that, from almost any perspective, the world (and humanity) is better off than ever before.
2. Two examples come to mind
   1. The green revolution: the work done here, back in the 50s and 60s, to develop new strains of corn, wheat and rice, that improved the yield of crops, have saved billions of lives (https://en.wikipedia.org/wiki/Green_Revolution).
   2. Horses vs cars: by the end of the 19th century, the streets of New York were covered in horse manure. This wasn't unique to New York (almost every major city had that issue). Dead horses were a major problem as well: in 1880, New York had 200,000 horses, and 15,000 dead horses were removed from the streets every year, (https://en.wikipedia.org/wiki/Great_Horse_Manure_Crisis_of_1894). The introduction of the car, and the subsequent decline of the horse, solved this problem.
   3. Surely, these advances led to new problems. But I think it's fair to say that the world is better off with cars and the green revolution than without.
3. I totally agree with you on the nuclear power example: it was unfairly demonized. 


I am biased, way before that, towards techno-optimism: I always believed that more technology, and better designs, will save the world. I always also believed in ultimate solutions, albeit now I feel it is rare to find one. I more into: solve the current problems, and then solve the emergent problems that arise from the solution.

I never subscribed to the idea that, somehow, if you stop and think about the consequences of the solution, you will find a better solution. There is a whole branch of mathematics called complex systems, that studies the emergent properties of systems (when something small is applied at scale), and how they are not predictable from the properties of the individual components. I think this is a good example of that. 

This is why, for example, I found documentaries like "The social dilemma" to be a ridiculously naive...sentimental garbage. The social behaviors that emerged from inventions like the "Like" button, or the "Retweet" button, are not predictable from the properties of the buttons themselves.

As for ethics, I always find this an ever-changing topic. I don't think there is a conflict between technology and ethics. As we, as species, evolve, so does our ethics. As new things are discovered, and new technologies are invented, we will have to adapt our ethics to them. I think the conflict arises when we try to apply old ethics to new technologies.
