---
title: Losing the fight for privacy
date: 2025-04-23 08:16:04 +0100
description: Reflections on how job hunting and freelancing steadily eroded personal privacy.
tags:
- personal
- reflections
draft: true
aliases:
- /2025/04/23/losing-the-fight-for-privacy.html
---
I always cherished the need for privacy, especially in the digital universe. I tried my best to balance what to show and what to hide. While I don't have concrete metrics on my success, I was feeling reasonably "okay" about my performance.

However, over the last year, in an effort to secure freelance contract (and later to find a job), I've probably revealed the details of the details about most aspects of my life to...everyone.

The number of times I submitted my CV under shaddy terms of services...hick, I don't even count to whom I submitted my CV, let alone who actually has it!

One - of many - scenarios I recall is that one morning I applied for a job in Safran (leading aerospace company in France), got rejected by lunch time, and a couple of minutes later, a recruiter - from a freelance platform that I never applied for - called me to see if I am interested in a freelance offer...in almost the same job I applied for!

Years of efforts are gone. Now I can pretend that I can fix this in the future. But even if I can protect the next phase of my life, the reality is that few years from now, if I need to find a job or promote a business or something, it is very likely that such a catastrophic phase will happen again. I don't have an effective strategy to avoid this at the moment.

The battle is effectively lost.

So, what can I do now? I think that instead of running away from it, that I should run towards it. If privacy is lost, then how can I leverage this to my best interest? That is the only question left.
