---
title: Torn apart
date: 2025-10-06 21:33:44 +0100
description: Draft reflections on social struggle, fear of exposure, and a fragmented model of self.
tags:
- personal
draft: true
aliases:
- /2025/10/06/torn-apart.html
---
One true fact of my existence is that there is a consistent struggle in every social dimension in order to achieve a below-average, barely a passing grade, level of norm. It's very strange when a mental model of the world is non-existent. 
Of course I can create my own model algorithmically, but it is full of rough edges and dysfunctional assumptions. No matter what improves I make, eventually reality and imagination meet in a colossal catastrophic collision.
I think I reached a point where most of what can be learned has been learned, and what is left are hard problem, with large impact and few examples to learn from.
I do live under a constant fear of revealing any part of myself, or communicating my feelings to others. Why not just try, you might think. Well, I did, many times, with a pristine unbroken failure rate of 100%.
