---
title: Marvin Minsky - MIT Lectures
date: 2025-03-30 16:02:18 +0100
description: First impressions from Marvin Minsky's MIT lectures on intelligence and free-form thinking.
tags:
- reflections
- personal
draft: true
aliases:
- /2025/03/30/marvin-minsky-mit-lectures.html
---
I dedicated this weekend to watch [Marvin Minsky lectures, *Society of mind*](https://ocw.mit.edu/courses/6-868j-the-society-of-mind-fall-2011/video_galleries/video-lectures/). It is a welcome detour from the currently widespread infection of low-quality, LinkedIn-style, cheap self-promotion, one-line-catcher posts.

This is the first time I listened to him. I've not read his legendary work before as well (a result of being a 90s kid I suppose). My impression is that Marvin Minsky is a complete nut job, and I have deeply fallen in love with his mind because of it!

# Marvin's Universe
Here are few things that attracted me

## Freedom from the experimental constraints
Marvin has no problem coming up with hypotheses and ideas that are not yet tested or hard to test. His mind wonders freely, like an artist, driven by logic, beauty and analogies.

His approach is closer to "practical philosophy", for the lack of a better term, than rigorous science.

The case that comes to mind when watching Marvin's lectures is [Leo Szilard](https://en.wikipedia.org/wiki/Leo_Szilard), who was well-known for his imagination and free-floating mind ([the dude literally was the first to imagined a nuclear chain reaction while standing in a traffic light...](https://www.scientificamerican.com/blog/the-curious-wavefunction/leo-szilard-a-traffic-light-and-a-slice-of-nuclear-history/)). Szilard was more of free thinker (let's go from A to Z then C, perhaps H, pass by W, then B), in contrast to Enrico Fermi (A->B->C->...) ([which led to several clashes between them](https://mag.uchicago.edu/science-medicine/clashing-colleagues)). 

Yet, many great achievements in physics came from the mix of Szilard's imagination and Fermi's rigor (I read an article about them long time ago in Scientific American, but I can't locate it unfortunately).

## Science fiction as evidence
You get the feeling that Minsky incorporates science fiction (the good ones, from the 50s) into his evidence. 

## Wide view over many different fields
He is comfortable diving into psychology, sociology, religion, meditation, perhaps even zoology and animal behavior, and a series continuous relentless criticism of neuroscience.

Marvin exposure to these domains allowed him to draw parallels, come up with analogies, and make conclusions about different aspects of intelligence.

## Long view on AI
One thing that caught my attention is when a student asked him whether we should be worried about the danger of AI. Marvin's response is that there are far more important and immediate issues to worry about, like Cybersecurity, and that AI in its current state doesn't represent a serious threat.

"But", he followed up, "when it will become a threat, it will happen quickly" (I am reciting it from memory, since I can't find the correct timestamp).

## Quality of the discussions and community
This is probably not Marvin-only issue, but a result of this MIT community. I liked the questions of the students, and their comfort engaging in a wide spectrum of topics with Marvin. 

I miss that. I always missed that. No number of online courses or books ever satisfied my thirst for a good quality conversation. It is this kind of community, this access, that acts as a great wall in the Game of Thrones.

# Final thoughts
This was a refreshing experience, seeing someone free from the fear of constraints, and enabling students to the same.

I compare this to myself: I am a very cautious person in my approaches. I seek testable ideas. Perhaps I would get his attitude if I've tenure? I don't know.
