---
title: What if baby Hitler killed baby super Hitler?
date: 2025-06-15 14:56:53 +0100
description: A reflection on ethics, complex systems, and the limits of simplistic causality.
tags:
- personal
aliases:
- /2025/06/15/what-if-baby-hitler-killed-baby-super-hitler.html
---
I see the world as a complex system. A characteristic of complex systems is the local & limited perception that the agents (aka: us) has, and the local impact of their actions.

This brings us to the philosophy of ethics: One of the ways ethics get astray is an unspoken assumption that our actions can have clear, simple to model, global impacts.

You probably have encountered this question from a smart-ass: What if you meet baby Hitler now? Would you kill him? Wouldn't humanity been better without him?

But, what if baby Hitler was critical in the history of humanity, because he killed baby Super Hitler? Super Hitler would have brought the humanity to its end.

What if, in all the parallel universes out there, a catastrophic event like our World War 2 was inevitable, but we got the least violent version out of it?

Equally probable (with equally infinite small probability), maybe the best way to eliminate the effect of Hitler would have been:
1. Giving his Dad a raise at work? He would have become a happier man, and the family would have prospered
2. His grandma should have chosen school A for his mom, which had more nurturing teachers, but she chose school B instead because it was conveniently on her way to work?
3. Maybe the president of the admission committee in the Vienna art school should have been more tolerant about his acceptance criteria?
4. Maybe the wife of the president of the admission committee in the Vienna art school should not have been a complete bitch about their planned redecoration of their house, which affected the dude's sleep, that led to him feeling crappy, and when he say Hitler application, he just couldn't focus on his merits?

Who is Hitler dad, mom, or any of the other individuals? I don't give a crap. The point is, we can go on and on and on about this, until hell freezes over.

You can't just reduce a vastly complex system to such meaningless statements, attractive due to their simplicity. People do this because it satisfies their feelings, the feeling of causality and meaning.

Language is supposed to free us, to enable us to communicate and coordinate better, but not to enslave us. If a word or an expression has no meaning, they must be retired. 

# Local effect
As part of being a complex system, an individual can truly perceive and affect (partially) his local surrounding, his actual sphere of influence. The utility of ethics, at this level, is sensible: we need a repertoire of tools and heuristics to handle this local surrounding, and ethics is part of this repertoire. 

The promoted impact of these tools though must be scrutinized: Being honest in an adversarial surrounding is probably a bad idea.

Thus, when ethics (or other tools and heuristics) are studied, they must be considered with the local context in which they are being used. An absolute is an absurdity.

Things make sense to a certain radius far from us: we can see a relationship between our actions and the outcomes. This is important to have in a sane environment: If I do action A, I expect outcome B.

In a crazy environment, the outcome changes often, thus we can't make sense of things anymore.

A healthy environment provide us with a good array of actions and favorable outcomes, at a feasible cost, in a predictable manner: Access to education, job opportunities, health services, affordable housing...etc.

The actions, outcomes, and their relation, will have to change eventually. The complex system is evolving, and it will impact the local surrounding eventually, changing the rules and norms. A healthy change is gradual and at an slow speed. Communities continue to grow and thrive. Fast changes are traumatic, and can disintegrate the fabric of the community.

Our actions have global impact that we can't understand, but a local impact that we can get false, yet useful, sense of reason about, in a sane environment. We should not generalize the local to the global. The global impacts the local.

#
