---
title: Little Angels
date: 2025-07-09 22:52:35 +0100
description: A personal story about two cats, attachment, care, and the pain of letting go.
tags:
- personal
- reflections
aliases:
- /2025/07/09/little-angels.html
---
These are stories of beautiful beings, who invaded my garden, uninvited, yet won my heart with their love and curiosity.

# Steve
Steve showed up in my garden early March 2025. He was playing, chasing the scent of birds. He didn't show fear of me: He saw me several times, made short eye contact, and then continued his business at an increasingly closer distances.

He explored climbing the almond tree in the garden. The first time, he got himself in trouble, seemingly stuck and unable to get down. I changed my choose, preparing to help him, but he worked the problem out very calmly. Soon after, he climbed again, every time higher and more riskier, and always found his way down. 

I left food for him one day (on the false premise that this convince him not to hunt the birds), and he invited himself into my home pretty quickly.

I never had such interaction with an animal before. A lot of curiosity, but also fear of diseases and unexpected reactions, all were in the playing in my mind. 

But the dude was chill, curious, and ready to push the push the boundaries. He explored each piece of the flat, and tried all the furniture.

Soon afterwords, I admired him. Steve was a character. Very confident, calm, excellent in his communication: whatever he wants, he would point at it with his paws, meow a couple of times.

The weather was cold and stormy that period, so I made a small spot for him indoors (a box, with a pillow and a blanket), hoping he would stay inside. I remember that day: he came, investigated the setup. I was setting on the ground observing what he was doing. Then he climbed on the box, looked at me...and he hugged me! It was such an alien experience. I left him to work in my office, and some time later I came to check on my little dude in his little box. He wasn't there, normal, he must have left. 
Then I went ti my bedroom, just to find him sleeping on the bed, partially under the cover. Clearly he thought that the box was for me, and I was leaving the bed for him :D

One time he pointed his claw at the apartment door. I took him for a tour inside the building (he is probably a foreign spy). Soon afterwords, he would use that to his benefit: when the gardner came, Steve would want to avoid the loud voices, he would ask me to cross the building from the inside. It's always calmer on the other side.

He liked to set next to each other in the garden, as if we were meditating. One time, there was a beautiful bee moving around, with an unusual long tongue. I was observing it. Steve stretched he his hands suddenly, caught the bee with his claws in a Ninja-style move, killed it, throw it body, all of this without moving an inch from his position, and returned back to his initial posture. It was a WTF moment: I admired him, although it was clear now that his enemy will suffer. 

Steve was definitely the man I would like to be when I grow up 😃

He liked to be carried. He would rub his forehead against mine. It was incredibly cute. He was done being carried, he would stretch his hands downwards.

Few weeks later, however, he was gone. Just like that.

What happened to him? Did he belong to someone who just moved? Was he stressed from the existence of Not Steve? Did he have an accident?

I searched for him a lot in the neighborhood, but no avail.

# Not Steve

"Not Steve" is the most influential being on my life. He is the first animal that stayed that long (close to 4 months now). I remember when I found him in my garden, during an awful stormy weather. He was so scared, setting there in the garden. I tried to carry him inside, he wouldn't let me. I left him some snacks nearby. He slowly went for them. But that took several days until he finally came on the terrace.

Soon afterwords, it was clear that I didn't like him. It took me a while to realize why. Timid, clumsy, wants love and connection but he doesn't know how. He kept a distance (but getting closer and closer), definitely not of an explorer as "Steve" (who explored the whole flat, in great detail, and then started to ask me to explore the whole building and stairs). My bias for Steve was obvious. In few occasions, Steve attacked Not Steve. I intervened immediately to stop it, but I was secretly approving such attacks.

But then I realized why I hated "Not Steve": he was a mirror of me. That is how I used to behave, and still is in many cases. I would like someone, but no one really would invest in me.

From that moment, I decided I want to invest in Not Steve. I want to explore his character, and get the best out of him.

This was a very long process, and I had no idea what was I doing exactly. My strategy was simple: keep feeding him, make very tiny pushes everyday towards him, and observe and react positively to his pushes as well. If I don't like something, I would stop the interaction.

There were some beautiful moments: the first time he set me lap. Gosh. The trust. It was amazing. He was still using his claws to fix himself on my legs. Some pyjamas pants were better than other for this painful experience.

Then, onetime, while sleeping on my lap, a loud car sound happened once, he got startled, bet my hand, and jumped way. It felt painful, betrayal, and scary. I stood, removed the water and food plats from the garden, and went inside. A cat bite? What is the protocol here? All kind of diseases went into my mind.
He set for many hours near the window. He seemed very sad.

Next day, he came, but I wasn't trusting. I opened, put the food and water outside, and immediately closed the window. 

The day after, I decided to pet him. My hands were fine, and I came to the conclusion that he was just scared when he bet me. He licked my wound when I was bitting him ❤️ and all was forgiven afterwords :)

Some time afterwords, I noticed bold spots on his had. I was concerned, but not alarmed. When the area of the spots increased over few days, then I decided I need to do something. After consulting friends, checking online, the most suitable way was to trap him inside the house, and let the vet examine him on the spot. 

And jeez, that was a scene...

For the 2 hours waiting time until the vet arrived, "Not Steve" was stressed as hell. He went through all phases of negotiation, trying to convince me to open the window: being a good cat, bad cat, sad lonely cat, cute cat...

When the vet finally examined him, he melted in her hands like a chocolate lava (the bastard!). He turned out to be in good health, and these spots were probably from a fight with other cats (I hope he was winning, and the fight was epic). But, two key infos came to light here: he wasn't chipped, and he was 5-6 years old. The second part was problematic, and unfortunately set us on a disastrous track. 

At that time, it was becoming likely that I will move to Sweden. I was seriously considering adopting him. But my potential life in Sweden was going to be different. I didn't have intention to have a garden again, or to live on the ground floor. I've a phobia from insects, I wasn't feeling comfortable opening the window. It wasn't working out. 

While I don't know anything about "Not Steve" history, we know he is an outdoor cat. Making a big shift for him to live indoors was a concern. There was also no fallback strategy. I can't just release him in the street of Stockholm during the winter.

I tried to lock him inside the house several times, he freaked out completely. He need that window open. I get it, and I hated the idea of constraining his freedom. He wanted access to the outside and the inside at the same time, which was a deal breaker for me. I can't live with my phobia of insects, and all the changes in the weather. But without any indication that he can survive indoor, I couldn't move on to adopt him.

After a lot of discussions with friends with cat experience, and after soul searching, I finally came to the conclusion that it will be best to find an accommodation for him in Toulouse.

That was the start for another long and fruitless journey, unfortunately. No one I know was looking to adopt a cat, and I don't know many people in the city already. I considered shelters, but friends warned me about the common policy in shelter, in that they will "execute" the cat if doesn't get adopted within few weeks. That scared the hell out of me.

I decided then it is better for him to stay where he is. This is the least risky option. What I can do from that moment on is to facilitate that, and give him the best chance for survival: good food, medical care, and continue socializing him. I've also put a good word for him with the potential new renters, and I planned to communicate with them after I leave, hoping that this, beside his new skills, will secure him a nice place and continuous care.

At least, that is what I imagined, until he uncovered my place, thanks to the fucking dishwasher. 

I was in the process of selling the furniture. It was clear that he noticed the absence of the armed chair. This is where we usually set, play and nape. I tried to deal with his obvious stress by playing more with him, and feeding him more snacks, which he ate quickly...so quickly in fact that he ended throwing up all his food, undigested, several times.

Things were looking shit.

I think he realized the endgame when I was selling the dishwasher. He came from outside, yelling at me, trying to stop me from removing the dish washer. I tried to calm him down, but he was pretty agitated. It was a strange moment. After I helped the buyers loading it in their car, he was still in the garden, observing. But by the time I cleaned the new empty place, he was gone. 

He bailed. He disappeared. Didn't show up in my garden since. It has been almost 5 days now. I brought him all kind of delicious treats, but this chapter was closed.

<!-- The signs of this emerging realization, however, started earlier, in terms of extra stress, throwing up undigested food. When I solve the armed chair, he was clearly disturbed. The armed chair is where I would normally set, where he would come, jump on my legs, set on my lap, and cuddle, hug, sleep and play. He realized that where I am going, he is not going. This is the end of the road. -->


Of course, that is my understanding of it, the reality from his side is probably different. 

I don't know how to express this. I deeply miss him. He is a great being, who helped me through a very difficult phase in my life. He was consistent and persistent. He hassled his way into my life, one step at a time. He is loving, caring, and deserved better than my stupid rational.

# Reflections

My philosophy in life over the last few years is to appreciate things for what they are: the friends who show up in my life, and the friends who...slip away from my life. I don't own people, and I can be grateful for the good time we had.

There were many cracks in this over the years, but it became clear that it is fatal. Life is about acquisitions and ownership. Anything of interest must be either owned, or abandoned if out of reach, but merely observing and interacting is a waste of everyone's time otherwise. 

Deep inside, I feel Not Steve wanted to be adopted. He did all what is needed. He is a good cat. I gave him all the wrong signals, under shit rational pretenses. Once the contrast between imagination and reality became clear, his simple objective and clear plan versus my ever-changing objectives and convoluted plan, he chose out.

It was also another huge slap on my face for moving away, and that it is for the determent of my surrounding, and me as a consequence. Investing in life requires deep roots, and my roots are very wide, yet shallow.

This issue, unfortunately, had far reaching negative consequences. From one side, it brought to the surface attitudes of mockery and cruelty in some of my close friends: they either dismissed any such relationship, or didn't appreciate at least that there are things that they didn't understand, or appreciate that this is how I feel, and that alone is enough.

Failure to be curious is the undoing of life.

I am less trusting (or willing to hear) other people's opinion and advice. The out-of-my-context opinions, resulting in low-quality ideas to insensitive and rude expressions, all of this amplified by inability to express my feelings, has contributed to my detriment. 

More friends need to be filtered out. The shrinkage of social circle will continue, towards the concentration around fewer, yet high-quality, individuals.
